/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Upgrades": "升级",
    "upgrades Existing": "现有升级",
    "Vintage Virus": "古病毒",
    "Description:": "描述:",
    "A flu strain resistant to most medicen. It was released when scientists cracked a space rock open.": "一种对大多数药物都有抗药性的流感病毒。它是科学家敲开一块太空岩石时释放出来的。",
    "A highly contagious flu strain that causes people to spontaniously combust after two days.": "一种高度传染性的流感病毒株，可使人在两天后自燃。",
    "A massive wave that used to be the nightmare of sailors, just like an 'ex-wife' it is known to take more than half of your belonings.": "巨大的海浪曾经是水手的噩梦，就像“前妻”一样，它夺走了你一半以上的财产。",
    "A mild summer thunderstorm, that strikes when people say 'We don't have Coca Cola, is Pepsi also ok?'.": "一个温和的夏季雷雨，当人们说“我们没有可口可乐，百事可乐也可以吗？”",
    "A powerful storm system with strong winds and heavy rain.": "这是一个强大的风暴系统，伴随着强风和暴雨。",
    "A professional salesman goes around trying to sell 'death buttons' to people. If they click on the button, they get 1 million, but one person dies..": "一个专业的推销员四处推销“死亡按钮”。如果他们点击按钮，他们会得到100万，但会有一人死亡。",
    "A shocking ball white or black concentrated lightning, depending on its color people seem to treat it differently.": "一个令人震惊的球，白色或黑色集中闪电，取决于它的颜色，人们似乎对待它不同。",
    "A space rock entering the Earth's atmosphere, but as long as we 'don't look up' it is probably not there.": "一颗太空岩石进入地球大气层，但只要我们“不抬头”，它就可能不在那里。",
    "A space rocks the size of the one that killed the dinosaurs entering the Earth's atmosphere. But it could be filled with gold, maybe ...": "一颗太空岩石的大小与杀死恐龙的那颗一样，进入了地球大气层。但它可能装满了金子，也许……",
    "A spontanious rupture in the Earth's crust creating a new volcano. Each volcano will get a new name just like: 'Eyjafjallajökull' .": "地壳的自发破裂产生了一座新的火山。每个火山都会有一个新名字，比如：“Eyjafjallajökull”。",
    "A sudden and violent shaking of the ground, frequently occurs when 'your mom' passes by.": "当“你妈妈”经过时，经常会发生突然而剧烈的地面晃动。",
    "An uncontrolled fire spreading rapidly, just like an STD on a festival.": "一场失控的大火迅速蔓延，就像节日里的性病一样。",
    "Animals abandoned by their owners now seek revenge against the human race for abandoning them.": "被主人遗弃的动物现在开始报复遗弃它们的人类。",
    "Back from the past to inflict pain.": "从过去回来造成痛苦。",
    "Chickens not only give eggs now, but also the flu.": "现在鸡不仅下蛋，还会传染流感。",
    "Gravitational anomalies that strike all around the world. Beyblade battles are much more difficult now, ... and a lot of poeple die.": "世界各地都有重力异常现象。Beyblade的战斗现在更加困难了…很多人因此丧命。",
    "Lightning speeds automated tics speed up.": "闪电般的速度，自动抽动加速。",
    "Lightning strikes splits into multiple strands.": "雷击分成多股。",
    "Magicians all over the world fail at their magic tricks, resulting in people being split on stage, magicians drowning, and bunnies being squished in hats...": "世界各地的魔术师都在他们的魔术中失败，导致人们在舞台上分裂，魔术师溺水，兔子被压在帽子里……",
    "Massive solar flare that disrupts all electronic devices leading to mass suicides among the professional gaming community.": "大规模的太阳耀斑破坏了所有电子设备，导致职业游戏社区的大规模自杀。",
    "Pig flu was the vegans answer to people who did not want to switch.": "猪流感是素食主义者对那些不想转变的人的回答。",
    "Random blizzards that strike a moments notice with no warning. '#See global warming is fake, I am cold now!' ...": "突如其来的暴风雪，毫无预警。“看，全球变暖是假的，我现在很冷！”“…",
    "The one thing that could make mosquitos more hated, they now spread the a dangerous flu virus.": "蚊子现在传播一种危险的流感病毒，这可能会让人们更讨厌蚊子。",
    "Toasters sometimes explode when people are trying to make toast. 'There is no such thing as free lunch'.": "当人们试图烤面包时，烤面包机有时会爆炸。“天下没有免费的午餐”。",
    "Upgraded the flu virus, Covid, or something else?.": "升级了流感病毒，新冠病毒，还是别的什么？",
    "Widespread flooding caused by heavy rainfall #more proof that global warming is fake.": "强降雨导致大范围洪水#更多证据证明全球变暖是假的。",
    "Winds so wild and fast that they can catch 'Max Verstappen'.": "风如此猛烈，以至于他们可以抓住“马克斯·维斯塔潘”。",
    "Cult": "异教",
    "Gems:": "宝石:",
    "Cost:": "成本:",
    "Config": "配置",
    "Click Power and how it works": "单击“电源”及其工作原理",
    "DeathPoints:": "死亡点:",
    "Deathpoints": "死亡点",
    "Death god": "死神",
    "Death Dealer": "死亡使者",
    "Lightning helmet": "闪电头盔",
    "lightning Kills": "雷击致死",
    "lightning Kills Per Click": "闪电击杀每一次点击",
    "Lightning King": "闪电之王",
    ": wind": ": 风",
    ": beast": ": 兽",
    ": poison": ": 毒",
    ": water": ": 水",
    ": lightning": ": 雷",
    ": fire": ": 火",
    ": earth": ": 土",
    ": all": ": 全部",
    "Price": "价格",
    "Relics": "遗物",
    "Remove music": "移除音乐",
    "Reset Save": "重置进度",
    "Score": "分数",
    "Shop": "商店",
    "Stats": "统计",
    "Stats & Achievements": "统计 & 成就",
    "Summer Storm": "夏季风暴",
    "water": "水",
    "water,wind": "水,风",
    "wind": "风",
    "Tutorial": "教程",
    "Kills:": "击杀:",
    "Kitchen Killer": "厨房杀手",
    "Load": "加载",
    "lvl": "等级",
    "Name:": "名称:",
    "Living:": "存活:",
    "lightning,wind": "雷,风",
    "lightning,fire": "雷,火",
    "Lightning Lord": "闪电领主",
    "Mass Flooding": "大规模的洪水",
    "Metal Ring": "金属戒指",
    "more info": "更多信息",
    "Normal numbers": "正常数字",
    "Passive Kills:": "被动击杀：",
    "poison": "毒",
    "Total clicks": "总计点击",
    "Total click kills": "总计点击击杀",
    "Worshipper:": "崇拜者:",
    "Earth Axe": "土斧",
    "earth,space": "土,太空",
    "Each divinity will multiply your clickpower by itself (3 divinities = clickpower *4). Each divinity will increase your passive power abilities by 75%!": "每个神将乘以自己的点击量（3个神=点击量*4）。每个神将增加你的被动能量技能75%！",
    "electricity,fire": "电,火",
    "Events": "事件",
    "Everything!": "一切!",
    "Kills": "击杀",
    "Kill your first human.": "杀死你的第一人。",
    "Lava Lord": "熔岩领主",
    "Worshipper": "崇拜者",
    "Remove SFX": "移除音效",
    "See Stats": "查看统计",
    "Remove passive popup": "移除被动弹框",
    "total upgrades bought": "购买的升级总数",
    "Reincarnate ": "转生 ",
    "Reincarnation will reset all your progress, you will only get to keep your relics, in return you will also get Divinties based on your number of kills!": "转世将重置你所有的进度，你将只得到你的遗物，作为回报，你也将得到基于你的击杀数量的神！",
    "passive": "被动",
    "Passive kills": "被动击杀",
    "Passive kills per minute": "被动击杀每分钟",
    "natural deaths": "自然死亡",
    "Minimize": "最小化",
    "Maximize": "最大化",
    "natural births": "自然出生",
    "No microtransaction here! But if you want you can:": "这里没有微交易！但如果你愿意，你可以：",
    "Boots worn by those who traverse the most treacherous terrains. These boots grant the wearer extra poison powers due to their intense smell, increasing passive poison kills by 5% per level.": "那些穿越最危险地形的人穿的靴子。这些靴子因其强烈的气味而赋予穿戴者额外的毒力，每级增加5%的被动毒击杀。",
    "fire": "火",
    "A hat woven from everyday straw, its is known for protecting people from sunburn. It buffs the power of the wind. Wearing this hat can increase your passive wind power by 5% per level.": "这是一种用日常稻草编织而成的帽子，以防止晒伤而闻名。它增强了风的力量。戴上这顶帽子每升一级可以增加5%的被动风力。",
    "Mjölnir, the hammer of Thor, channels the power of lightning, allowing you to summon and control thunderbolts even better 100% increase to all future click power. (And this per level!)": "Mjölnir，雷神之锤，引导闪电的力量，让你召唤和控制雷电甚至更好的100%增加所有未来的点击能力。（每级都是如此！）",
    "Sandals crafted from enchanted wood, providing the wearer with the power of lightning. Wearing these sandals can increase your passive and active lightning power by 5% per level.": "由魔法木材制成的凉鞋，为穿戴者提供闪电的力量。穿着这些凉鞋每级可以使你的被动和主动闪电力量提高5%。",
    "Grunt": "步兵",
    "Armor crafted from the scales of a mighty dragon, offering unparalleled protection and strength. Wearing this armor can increase your passive and active power by 20% per level.": "由巨龙的鳞片制成的盔甲，提供无与伦比的保护和力量。穿戴此护甲可以使你的被动和主动力量每级提高20%。",
    "An axe forged from the heart of the earth, capable of causing tremors with each strike. Wielding this axe can increase your passive earth kills by 35% per level.": "以大地之心锻造而成的斧头，每一击都能引起震动。使用此斧每级增加35%的被动土击杀。",
    "A sword forged from the purest ice, capable of freezing enemies in their tracks. Wielding this sword can increase your passive ice and water kills by 30% per level.": "一把用最纯净的冰锻造的剑，能够将敌人冻结在他们的足迹上。使用这把剑可以使你的被动冰和水击杀每级提高30%。",
    "A bow that harnesses the power of the wind, capable of firing arrows with gale force. Wielding this bow can increase your passive wind kills by 27.5% per level.": "一种利用风的力量的弓，能够射出具有大风威力的箭。使用此弓可以每级增加27.5%的被动风击杀。",
    "A cloak infused with the power of lightning, enhancing agility and speed. Wearing this cloak can increase your lightning power by 3% of your passive kills per minute.": "一件充满闪电力量的斗篷，增强敏捷和速度。穿上这件斗篷可以使你的闪电威力每分钟增加被动击杀数的3%。",
    "A helmet adorned with beastly features, providing unmatched beastly ferocity. Wearing this helmet can increase your passive beast based kills by 65% per level.": "一个带有野兽特征的头盔，提供了无与伦比的野兽凶残。戴上这个头盔可以每级增加65%的被动野兽击杀。",
    "A helmet charged with the power of lightning, providing superior agility. Wearing this helmet can increase your active lightning power by 45% per level.": "一顶充满闪电力量的头盔，提供卓越的敏捷性。佩戴此头盔每级可使你的有效闪电能量提高45%。",
    "A lab experiment goes wrong, creating a giant hamster that wreaks havoc in the city.": "一个实验室实验出了问题，创造了一只巨大的仓鼠，在城市中肆虐。",
    "A mace imbued with the essence of fire, capable of incinerating rocks with a single touch. Wielding this mace can increase your passive fire kills by 30% per level.": "一种充满火焰的权杖，一碰就能把岩石烧成灰烬。使用这把狼牙棒可以每级增加30%的被动火焰击杀。",
    "A mad scientist’s experiment goes wrong, creating a monster that terrorizes the city.": "一个疯狂科学家的实验出了问题，创造了一个恐吓城市的怪物。",
    "A mass alien abduction event that abducts people all over the world": "一场大规模的外星人绑架事件，绑架了世界各地的人",
    "A mysterious virus turns people into zombies, causing chaos everywhere.": "一种神秘的病毒把人变成僵尸，到处造成混乱。",
    "A poisons cloak enhancing the power of your diseases by 15% per level.": "一件毒药斗篷每升一级使你的疾病威力提高15%。",
    "A ring crafted from enchanted metal, channeling the power of lightning. Wearing this ring can increase your active lightning power by 5% per level.": "一枚由魔法金属制成的戒指，可以传递闪电的力量。戴上这个戒指可以每级增加5%的有效闪电能量。",
    "A ring forged in the depths of the underworld, granting its wearer the power of ancient demons. Wearing this ring can increase your all your power by 15% per level.": "一枚在冥界深处锻造的戒指，赋予佩戴者远古恶魔的力量。戴上这枚戒指，每升一级可以增加15%的能量。",
    "A scarf imbued with the essence of fire, providing its wielder a fiery aura. Wearing this scarf can increase your passive fire attacks by 10% per level.": "一种充满了火的本质的围巾，给它的持有者提供一个火的光环。戴上这条围巾，每升一级可以使你的被动火力攻击提高10%。",
    "A scepter unwieldable by mortals due to the toxicity of the fumes surrounding it. Wielding this scepter can increase your passive disease power by 30% per level.": "一根凡人无法使用的权杖，因为它周围的烟雾具有毒性。使用此权杖可以使你的被动疾病力量每级提高30%。",
    "A simple yet versatile stick, 'its better than nothing'. Using this stick can increase your passive and active power by 1% per level.": "一根简单但用途广泛的棍子，“总比没有好”。使用此棒可以使你的被动和主动能量每升一级提高1%。",
    "A staff crackling with the power of lightning, capable of summoning thunderous strikes. Wielding this staff can increase your lightning click kills by 3950 per level.": "一根带有闪电威力的噼啪作响的杖，能够召唤雷鸣般的打击。使用此杖每级可使你的闪电击杀增加3950次。",
    "Acolytes Alive": "活着的信徒",
    "Activate": "激活",
    "Activate:": "激活:",
    "active": "主动的",
    "adjust volume": "调整音量",
    "Age: 14": "年龄：14岁",
    "Alien Affliction": "外星人的苦难",
    "Alive": "活着的",
    "all - also added to all elements": "All -也加到所有元素中",
    "alltypes": "所有类型",
    "Animal Avenger": "动物复仇者",
    "Anomaly Artist": "异常艺术家",
    "Apocalypse Now": "现代启示录",
    "Aqua Annihilator": "水湮灭器",
    "Arcane Annihilator": "奥术歼灭者",
    "Armory": "军械库",
    "Asteroid Annihilator": "小行星歼灭者",
    "Avian Annihilator": "禽流感歼灭者",
    "Bacon Banisher": "培根放逐者",
    "beast": "野兽",
    "Beast Helmet": "野兽头盔",
    "Beggar’s cloak": "乞丐披风",
    "Bill": "比尔",
    "Bird Flu Baron": "禽流感男爵",
    "bla blab": "废话连篇",
    "Blaze Beginner": "火焰初学者",
    "Blaze Bringer": "火焰使者",
    "Blazing Fire Flu": "烈焰流感",
    "Blizzard Bringer": "暴风雪使者",
    "Blizzard storm": "暴风雪",
    "Buff Element": "Buff元素",
    "Buzzing Butcher": "嗡嗡作响的屠夫",
    "Celestial Catastrophe": "天灾",
    "Clown Uprising": "小丑起义",
    "Clowns from all over the world unite and start a rebellion against non-clowns.": "来自世界各地的小丑们联合起来，开始反抗非小丑。",
    "Combustion Conqueror": "燃烧征服者",
    "Combustion Craze": "燃烧热潮",
    "Comet Conqueror": "彗星征服者",
    "Cosmic Contagion": "宇宙传染病",
    "Cosmic Crusher": "宇宙粉碎者",
    "Cyclone Crusher": "旋风粉碎者",
    "Cyclone Sovereign": "旋风之王",
    "D. Grump get elected for president of the united states": "D.格朗普当选美国总统",
    "days in game": "游戏天数",
    "Death button": "死亡按钮",
    "Death Incarnate": "死亡的化身",
    "Death's Right Hand": "死神的右手",
    "Deluge Demolisher": "洪水清理机",
    "Demon Ring": "恶魔戒指",
    "Destruction Dealer": "破坏者",
    "Devastating Tsunami": "毁灭性的海啸",
    "Disaster Card events": "灾难卡片事件",
    "Divinities": "神祗",
    "Dragon Scale Armor": "龙鳞铠甲",
    "Each Acolyte sacrifes 5 People per level.": "每个随从每级牺牲5个人。",
    "earth": "地球",
    "Earthquake": "地震",
    "Earthquake Emperor": "地震皇帝",
    "Egg-celent Executioner": "蛋精刽子手",
    "Electric Executioner": "电动刽子手",
    "electricity": "电",
    "Electrifying Executioner": "令人振奋的刽子手",
    "Electro Emperor": "电光皇帝",
    "Equipment area": "装备区",
    "Erupting Volcano": "火山喷发",
    "Eruption Expert": "火山专家",
    "Falling Meteor": "流星坠落",
    "Feathered Fatality": "羽状死亡",
    "Ferocious Hurricane": "飓风肆虐",
    "Fire Mace": "火权杖",
    "Fire Scarf": "火之围巾",
    "fire,earth": "火、土",
    "fire,earth,space": "火、土、空间",
    "fire,water": "火,水",
    "Firestorm Fiend": "风暴恶魔",
    "Firestorm Fighter": "风暴战士",
    "First Strike": "第一次罢工",
    "Flame Overlord": "火焰领主",
    "Flare Fighter": "耀斑战斗机",
    "Flare Forger": "耀斑伪造者",
    "Flood Founder": "洪水创始人",
    "Flu Fiend": "流感恶魔",
    "Flu Fighter": "流感斗士",
    "Flu Overlord": "流感霸主",
    "Force of Nature": "自然之力",
    "Frost Fiend": "冰霜恶魔",
    "Galactic Germ": "银河细菌",
    "Gale Giver": "疾风赐予者",
    "Giant Hamster Rampage": "巨型仓鼠暴走",
    "Gravitational anomalies": "引力异常",
    "Gravitational Goliath": "引力巨人",
    "Gravity Goof": "重力断层",
    "Grump for president": "特朗普竞选总统",
    "Ham Harbinger": "火腿先锋",
    "Hammer of Thor": "雷神之锤",
    "Heavy Flu": "重型流感",
    "Here you can look at the cultists that you hired, they will collect worshipper for you. You can use the worshipper to purchase events.": "在这里你可以看到你雇佣的信徒，他们会为你收集礼拜者。你可以用礼拜者来购买事件。",
    "Hide Claimed Achievements:": "隐藏已领取成就：",
    "Hire cultist:   1.50  K": "雇佣信徒：1.5万",
    "Hire New Acolyte": "雇佣新助手",
    "Historic Harbinger": "历史先兆",
    "Hurricane Hero": "飓风英雄",
    "I want to impact developement!": "我想影响发展！",
    "Ice Emperor": "冰帝",
    "Ice Sword": "冰剑",
    "Idle Evil God": "闲散的恶神",
    "Illusion Instigator": "幻象煽动者",
    "Impact Initiator": "影响启动器",
    "Inferno Instigator": "地狱煽动者",
    "Insect Invader": "昆虫入侵",
    "Interstellar Infection": "星际感染",
    "It covers you, but does not have much use otherwise. The slight warmth provided increases your lightning power by 1% per level.": "它覆盖着你，但除此之外没有多大用处。轻微的温暖每升一级使你的闪电威力提高1%。",
    "Job: Employee": "工作：员工",
    "Kill your first 10,000 humans.": "杀死你的第一个10000人类。",
    "lightning": "闪电",
    "Lightning Cloak": "闪电斗篷",
    "lightning Cost": "闪电成本",
    "Lightning Count": "闪电次数",
    "Lightning Demi-god": "闪电的崇拜对象",
    "Lightning Emperor": "闪电皇帝",
    "Lightning Legend": "闪电的传说",
    "lightning level": "闪电水平",
    "Lightning Liberator": "闪电解放者",
    "lightning Passive Cost": "闪电被动成本",
    "lightning Passive Speed": "闪电无源速度",
    "Lightning Strike passive speed": "雷击被动速度",
    "Lightning Strike power": "闪电的力量",
    "Mad Scientist Experiment": "疯狂科学家实验",
    "Magic Malefactor": "魔法破坏者",
    "Magma Monarch": "岩浆君主",
    "Mass Alien Abduction": "大规模外星人绑架",
    "Master of Mayhem": "混乱大师",
    "Meteor Menace": "流星威胁",
    "MOAM, Mother of all Meteors": "MOAM，所有流星之母",
    "Mosquito Menace": "蚊子的威胁",
    "Mysterious space Flu": "神秘的太空流感",
    "No more magic": "不再有魔法",
    "Nova Nemesis": "新星“复仇者”",
    "Nova Neophyte": "新星新人",
    "Number of Acolytes": "信徒数量",
    "Ocean Obliterator": "海洋毁灭者",
    "Ocean Overlord": "海洋霸王",
    "Pandemic Pro": "大流行专业",
    "Passive Aggressor": "被动的侵略者",
    "Passive Count": "被动计数",
    "Passive Demi-god": "被动的半神",
    "Passive Emperor": "被动的皇帝",
    "Passive Executioner": "被动的刽子手",
    "Passive King": "被动的国王",
    "Passive Lord": "被动领主",
    "Passive Perfectionist": "被动完美主义者",
    "Passive upgrade kills per Minutes (toggle)": "被动升级每分钟击杀数（切换）",
    "Past Plague": "昔日瘟疫",
    "Pet Punisher": "宠物惩罚者",
    "Physics Phenom": "物理奇才",
    "Pig Plague": "猪病",
    "Plague Pro": "鼠疫专业",
    "Planet Pulverizer": "行星粉碎机",
    "Poison Cloak": "毒药斗篷",
    "poison,beast": "毒药,野兽",
    "poison,fire": "毒，火",
    "poison,old": "毒药,老",
    "poison,old,space": "毒药,老,空间",
    "Pork flu": "猪流感",
    "Pork Pestilence": "猪肉瘟疫",
    "Poultry Plague": "家禽瘟疫",
    "Putni gets elected during a free \"election\" in Russia": "普京在俄罗斯的自由“选举”中当选",
    "Putni is president of Russia": "普京是俄罗斯总统",
    "Quake Conqueror": "地震征服者",
    "Quake Quencher": "地震冷却器",
    "Radiation Reaper": "辐射收割者",
    "Raging Wildfire": "森林大火",
    "Release cultee from service": "释放被崇拜的人",
    "Retro Reaper": "复古的收割者",
    "Revenge of the strays": "流浪狗的复仇",
    "Revenge Ruler": "复仇的统治者",
    "Revenge Starter": "复仇起动器",
    "Rider of the Apocalypse": "天启骑士",
    "Robot Rebellion": "机器人叛乱",
    "Robots gain sentience and start a rebellion against humans.": "机器人获得了感知能力，开始反抗人类。",
    "Sacrifice festival": "献祭的节日",
    "Sea Slayer": "海洋杀手",
    "See Armory": "看到军械库",
    "Seismic Slayer": "地震杀手",
    "Sent cultee to training": "送学员去培训",
    "Shockwave Slayer": "冲击波杀手",
    "Show all achievements not achieved:": "显示所有未完成的成就：",
    "Silent But Deadly": "无声但致命",
    "Sneeze Starter": "打喷嚏起动器",
    "Snowstorm Slayer": "暴风雪杀手",
    "Solar flares": "太阳耀斑",
    "Solar Saboteur": "太阳能破坏者",
    "Space Plague Sovereign": "太空瘟疫君主",
    "Space Rock Reaper": "太空岩石死神",
    "Space Scourge": "空间祸害",
    "Spanish Flu": "西班牙流感",
    "Spell Slayer": "拼写杀手",
    "Spontanious lightning nova": "自发闪电新星",
    "Spontanious toaster combustion": "烤面包机自燃",
    "Storm Bringer": "风暴带来",
    "Storm Sovereign": "风暴主权",
    "Storm Sprinter": "风暴短跑运动员",
    "Storm Supplanter": "风暴吞噬器",
    "Straw Hat": "草帽",
    "Stray Slayer": "流浪杀手",
    "Sun Scourge": "太阳灾害",
    "Superhero Battle": "超级英雄战斗",
    "Superheroes and supervillains clash in an epic battle, causing collateral damage.": "超级英雄和超级反派在一场史诗般的战斗中发生冲突，造成了附带伤害。",
    "Support the developer!": "支持开发者！",
    "Swine Slayer": "杀猪人",
    "Tempest Tyrant": "风暴暴君",
    "The bird flu is back": "禽流感卷土重来",
    "The mosquito flu": "蚊子流感",
    "Thunder Staff": "雷声的员工",
    "Thunder Thrasher": "雷霆打谷机",
    "Thunderous Applause": "雷鸣般的掌声",
    "Tidal Tyrant": "潮汐暴君",
    "Time-Travelling Terror": "穿越恐怖",
    "Toast Terrorist": "烤面包的恐怖",
    "Toaster Tormentor": "烤面包机折磨",
    "Toaster Tyrant": "烤面包机的暴君",
    "Tornado Tyrant": "龙卷风暴君",
    "Total triggers allowed:": "累计可触发次数：",
    "Toxic staff": "有毒杖",
    "Tremor Tyrant": "震颤暴君",
    "Trick Terrorist": "恶作剧恐怖分子",
    "Tsunami Terrorist": "海啸恐怖分子",
    "Twister Terrorist": "龙卷风恐怖分子",
    "Virus Veteran": "病毒老兵",
    "Volcanic Vanquisher": "火山征服者",
    "Volcano Virtuoso": "火山艺术大师",
    "Vortex Villain": "漩涡恶棍",
    "Wanderer's Boots": "流浪者的靴子",
    "Water Warlord": "水军战神",
    "Wave Wrecker": "破浪者",
    "Wild Tornado": "狂野龙卷风",
    "Wildfire Warlord": "野火军阀",
    "Wind Bow": "风之弓",
    "Winter Wraith": "凛冬魔灵",
    "Wooden Sandals": "木制凉鞋",
    "Wooden Stick": "木棒",
    "xMax": "xMax",
    "you can get 0.0 divinities if you reincarnate now!": "如果你现在转世，你可以得到0.0个神！",
    "Zombie Apocalypse": "僵尸启示录",
    "Zues": "魔界",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "NaN": "NaN",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Total kills: ": "累计杀死: ",
    "Ability Type: ": "能力类型: ",
    "Description: ": "描述: ",
    "Status: ": "状态: ",
    "Kills: ": "击杀: ",
    "Name: ": "名称: ",
    "Worshipper: ": "崇拜者: ",
    "Divinities:": "神祇:",
    "Total worshipper: ": "总计崇拜者: ",
    "(KPS: ": "(每秒击杀(KPS): ",
    "Upgrade effect: ": "升级效果: ",
    "Level: ": "等级: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "% of the world": "% 世界",
    " kills per click.": " 击杀每次点击。",
    " passive speed up!.": " 被动速度提升!.",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)  K$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Kill our first (.+) humans.$/, '击杀你的前 $1 人。'],
    [/^Kill (.+) humans with Erupting Volcano.$/, '使用 火山喷发 杀死 $1 人。'],
    [/^Kill (.+) humans with No More Magic.$/, '使用 没有更多的魔法 杀死 $1 人。'],
    [/^Kill (.+) humans with Mysterious Space Flu.$/, '使用 神秘的太空流感 杀死 $1 人。'],
    [/^Kill (.+) humans with Devastating Tsunami.$/, '使用 毁灭性的海啸 杀死 $1 人。'],
    [/^Kill (.+) humans with Gravitational Anomalies.$/, '使用 引力异常 杀死 $1 人。'],
    [/^Kill (.+) humans with Wild Tornado.$/, '使用 狂野龙卷风 杀死 $1 人。'],
    [/^Kill (.+) humans with Mass Flooding.$/, '使用 大规模洪水 杀死 $1 人。'],
    [/^Kill (.+) humans with Summer Storm.$/, '使用 夏季风暴 杀死 $1 人。'],
    [/^Kill (.+) humans with Spanish Flu.$/, '使用 西班牙流感 杀死 $1 人。'],
    [/^Kill (.+) humans with Falling Meteor.$/, '使用 流星坠落 杀死 $1 人。'],
    [/^Kill (.+) humans with Toaster Combustion.$/, '使用 烤面包机燃烧 杀死 $1 人。'],
    [/^Kill (.+) humans with Solar Flares.$/, '使用 太阳耀斑 杀死 $1 人。'],
    [/^Kill (.+) humans with Raging Wildfire.$/, '使用 森林大火 杀死 $1 人。'],
    [/^Kill (.+) humans with Revenge of the Strays.$/, '使用 复仇的流浪狗 杀死 $1 人。'],
    [/^Kill (.+) humans with MOAM, Mother of All Meteors.$/, '使用 MOAM，流星之母 杀死 $1 人。'],
    [/^Kill (.+) humans with Spontaneous Lightning Nova.$/, '使用 自发闪电新星 杀死 $1 人。'],
    [/^Kill (.+) humans with Pork Flu.$/, '使用 猪流感 杀死 $1 人。'],
    [/^Kill (.+) humans with the heavy flu.$/, '使用 重型流感 杀死 $1 人。'],
    [/^Kill (.+) humans with heavy flu.$/, '使用 重型流感 杀死 $1 人。'],
    [/^Kill (.+) humans with Earthquake.$/, '使用 地震 杀死 $1 人。'],
    [/^Kill (.+) humans with Ferocious Hurricane.$/, '使用 飓风肆虐 杀死 $1 人。'],
    [/^Kill (.+) humans with lighting strikes.$/, '使用 雷击 杀死 $1 人。'],
    [/^Kill (.+) humans with The Mosquito Flu.$/, '使用 蚊子流感 杀死 $1 人。'],
    [/^Kill (.+) humans with Blizzard Storm.$/, '使用 暴风雪 杀死 $1 人。'],
    [/^Kill (.+) humans with The Bird Flu is Back.$/, '使用 禽流感卷土重来 杀死 $1 人。'],
    [/^Kill (.+) humans with passive upgrades.$/, '使用 被动升级 杀死 $1 人。'],
    [/^Kill (.+) humans with Blazing Fire Flu.$/, '使用 烈焰流感 杀死 $1 人。'],
    [/^Accumulate (.+) death points.$/, '累计 $1 死亡点。'],
    [/^Upgrade effect: (.+) kills per minute.$/, '升级效果：每分钟 $1 击杀。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) gems$/, '$1 宝石'],
    [/^lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level: ([\d\.,]+)$/, '等级: $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^(.+) strike\/ (.+) Sec$/, '$1 击打\/ $2 秒'],
    [/^(.+) Worshipper$/, '$1 崇拜者'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);